import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Menu/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`overflow-x-hidden ${inter.className}`}>
        <Navbar />
        <main className="min-h-screen p-8 md:p-12 max-w-screen-xl m-auto ">
          {children}
        </main>
      </body>
    </html>
  )
}
